### ISSUE TITLE
Add link to webpage from GitHub repo description

### ISSUE THREAD

**Issue by fulldecent** [projectchicago/gastoken.io#1]
Add link to webpage from GitHub repo description

**Comment by fulldecent** [comment]
Reference: https://github.com/projectchicago/projectchicago.io/issues/2

**Comment by fulldecent** [comment]
Ping

**Comment by lorenzb** [comment]
@fulldecent Sorry for the delay in replying to you. We're overall pretty happy with this website. If you have typo fixes or specific suggestions for improvements, feel free to file an issue. 

Having said that, I don't think that the site merits an "edit this page on github" button. Like for projectchicago, we mainly use github for free hosting.
